#+TITLE: Compiler and Translator Design Project
#+OPTIONS: toc:nil num:nil

* Compiler and Translator Design Project

[[https://travis-ci.org/andschwa/uidaho-cs445][https://travis-ci.org/andschwa/uidaho-cs445.svg?branch=master]]
/Andrew Schwartzmeyer/

- University of Idaho - Department of Computer Science
- [[http://www2.cs.uidaho.edu/~jeffery/courses/445/syllabus.html][CS 445]]: Compiler and Translator Design, by Dr. Clinton Jeffery

This is a work-in-progress old-school compiler using Flex and Bison
for a subset of C++, dubbed "120++" as it should work for most code
written in CS 120, including basic classes.

This repo is located at: https://github.com/andschwa/uidaho-cs445

** Assignment #1: A Lexical Analyzer

Per the [[http://www2.cs.uidaho.edu/~jeffery/courses/445/hw1.html][requirements]], my initial goal was to create a lexical analyzer
(using [[http://flex.sourceforge.net/][Flex]]) for 120++.

** Assignment #2: A Syntax Tree

Per the [[http://www2.cs.uidaho.edu/~jeffery/courses/445/hw2.html][requirements]], my second goal was to write (or reuse) a 120++
grammar that works with Bison.

** Assignment #3: Semantic Analysis
Per the [[http://www2.cs.uidaho.edu/~jeffery/courses/445/hw3.html][requirements]], my third goal was to perform semantic analysis
(including populating symbol tables and type checking the expressions)
on the syntax tree.
